### ISSUE TITLE
1.20.2 Support?

### ISSUE THREAD

**Issue by devurose** [D1p4k/NetherPortalBoom#1]
Hey there! Is 1.20.2 support planned or should I look into alternatives? No rush, just thought I should poke about it :)
Thank you for your time, I love the mod!

**Comment by Dev0Louis** [comment]
I can implement support :)

**Comment by Dev0Louis** [comment]
But the Mod should just work, can you send the error you are getting?

**Comment by devurose** [comment]
Ah you know what after having rechecked, it totally does work out of the box! 
I think I just missed something in my initial installation process
That's what I get for staying up so late, that's on me lol

Have an amazing day, sorry for any confusion ^^
